export const Emoji = {
	a: '🇦', b: '🇧', c: '🇨', d: '🇩',
	e: '🇪', f: '🇫', g: '🇬', h: '🇭',
	i: '🇮', j: '🇯', k: '🇰', l: '🇱',
	m: '🇲', n: '🇳', o: '🇴', p: '🇵',
	q: '🇶', r: '🇷', s: '🇸', t: '🇹',
	u: '🇺', v: '🇻', w: '🇼', x: '🇽',
	y: '🇾', z: '🇿', 
	0: '0️⃣', 1: '1️⃣', 2: '2️⃣', 3: '3️⃣', 4: '4️⃣',
	5: '5️⃣', 6: '6️⃣', 7: '7️⃣', 8: '8️⃣', 9: '9️⃣',
	10: '🔟',
	'#': '#️⃣', '*': '*️⃣', '!': '❗', '?': '❓',
	'repeat': '🔁', 'repeat_one': '🔂', 'play_pause': '⏯️',
	'arrow_forward': '▶️', 'fast_forward': '⏩', 'rewind': '⏪',
	'arrow_backward': '◀️', 'arrow_up_small': '🔼', 'arrow_down_small': '🔽',
	'arrow_double_up': '⏫', 'arrow_double_down': '⏬', 'pause_button': '⏸️',
	'stop_button': '⏹️', 'record_button': '⏺️', 'eject_button': '⏏️',
	'infinity': '♾️', 'heavy_plus_sign': '➕', 'heavy_minus_sign': '➖',
	'heavy_division_sign': '➗', 'heavy_multiplication_x': '✖️',
	'forbidden': '🚫', 'mute': '🔇', 'speaker': '🔈', 'sound': '🔉',
	'loud_sound': '🔊', 'loudspeaker': '📢', 'mega': '📣',
	'bell': '🔔', 'no_bell': '🔕', 'cross': '❌',
	'music': '🎵', 'musical_note': '🎵', 'notes': '🎶',
	'mag': '🔍', 'mag_right': '🔎', 'trash': '🗑️',
	'clock1': '🕐', 'clock2': '🕑', 'clock3': '🕒', 'clock4': '🕓',
	'clock5': '🕔', 'clock6': '🕕', 'clock7': '🕖', 'clock8': '🕗',
	'clock9': '🕘', 'clock10': '🕙', 'clock11': '🕚', 'clock12': '🕛',
	'no_entry': '⛔', 'no_entry_sign': '🚫',
};
